version: "3.9"
services:
  tavana-site:
    image: registry.tech1a.co:81/repository/tech1a-docker-registry/tavana-site:latest
    networks:
      - omsnet
    ports:
      - 9037:3000
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 5
        delay: 10s
        order: start-first
      restart_policy:
        condition: any
        delay: 10s
        window: 20s

networks:
 omsnet:
    external:
      name: omsnet
